Add Tutorial Level Blockout (#17)
* added sprite

* moving enemy

added navigation layer
added enemy that can move between markers

* 0.0.0.2

* enemy is working. Light cone will be added later

* Added EnemyAI: PathFinding, Chase, Navigation Layer

Game Scene:
-Added ,,enemyMarkers" node containing four markers - You can change their position directly in game scene and attach each to enemy's script marker slots
-Added Enemy for testing

Game Scene's Tilemap:
-Added navigation layer for enemy's pathfinding

Groups:
-Added ,,player" global group

Collision Layer + Mask:
-Changed Tilemap Layer to 1
-Changed Player Layer to 2, Mask to 1 and 3
-Changed Enemy Layer to 3, Mask 1 and 2
-Changed Enemy's VisionArea Layer to 4, Mask 2

Those changes were made so multiple enemies can pass through each other, but not through player or walls

Enemy:
-Added Sprite, walking/chase animation
-Added PointLight2D - it was made as visual representation of enemy's LOS (Line of Sight)
-Added Patrol Mechanic up to 4 markers that can be put on a level
-Added Sprite, VisionArea2D, Enemies's PointLight2D - horizontal rotation, based on direction enemy is heading
-Added Pathfinding up to 4 markers
-Added Enemy's LOS in triangle shape
-Added Chase after the player mechanic
-Added Chase lose line of sight mechanic

While saving ,,EnemyAiScene" game engine outputs this ERROR message. It doesn't affect code or game itself, it is displayed, because markers that script/game engine is looking for, aren't in Enemy's scene, but in game scene.
  ERROR: scene/main/node.cpp:2354 - Parameter "common_parent" is null.

* suggested changes

* version that I like with idle animation

* git

* base

* gugugt

* check

* working version. problem with corners

* vision collission problem

* best version for now

* Update EnemyAi.cs

* finito?

* small bug

* ggg

* jest git

* Update EnemyAi.tscn

* added projectsettingsnaming

* merge conflict fixed

* XD

* working on new level

* Cleanup

* Restored .idea files

* Fixes Scenes folder case inconsistency

* Fixed Scripts folder case isssue

* Update .gitignore

* Add DeathScreen, Asset Cleanup

* name change

* Update .gitignore

* minor changes

* fixed

* fine version

* code is finished

* fixed ui

* Update .gitignore

* tutorial level blockout

---------

Co-authored-by: Henry of SWPS <jduzyk@st.swps.edu.pl>